# Hedgehog vAIDC - Terraform Module Metadata for Cloud Marketplace
# This file defines how variables appear in the Cloud Marketplace UI

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: hedgehog-vaidc
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Hedgehog Virtual AI Data Center (vAIDC)
    source:
      repo: https://github.com/afewell-hh/labapp
      sourceType: git
    version: 1.0.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.0.0"
    description: |
      Pre-configured lab environment for Hedgehog Fabric training.
      Includes VLAB with 7 SONiC switches, Grafana, Prometheus, ArgoCD, and Gitea.
    deploymentDuration:
      configurationSecs: 60
      deploymentSecs: 300
  content:
    documentation:
      - title: Getting Started Guide
        url: https://docs.hedgehog.cloud/vaidc/getting-started
      - title: Course Materials
        url: https://hedgehog.cloud/learn
    subBlueprints: []
    examples: []
  interfaces:
    variables:
      - name: project_id
        description: The Google Cloud project ID where resources will be created
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: Deployment name for Cloud Marketplace
        varType: string
        required: false
      - name: zone
        description: GCP zone for deployment
        varType: string
        defaultValue: us-west1-c
      - name: machine_type
        description: Machine type (minimum 16 vCPUs, 32GB RAM)
        varType: string
        defaultValue: n1-standard-32
      - name: network
        description: Network for the VM
        varType: string
        defaultValue: default
      - name: subnetwork
        description: Subnetwork for the VM
        varType: string
        defaultValue: ""
      - name: boot_disk_size_gb
        description: Boot disk size in GB
        varType: integer
        defaultValue: 300
      - name: boot_disk_type
        description: Boot disk type
        varType: string
        defaultValue: pd-balanced
      - name: source_image
        description: Source VM image
        varType: string
        defaultValue: projects/teched-473722/global/images/hedgehog-vaidc-v20260114
        connections:
          - source:
              source: marketplace
              spec: ET_GCE_DISK_IMAGE
      - name: firewall_source_ranges
        description: Source IP ranges for firewall rules
        varType: list(string)
        defaultValue:
          - 0.0.0.0/0
    outputs:
      - name: vm_name
        description: Name of the vAIDC VM instance
      - name: external_ip
        description: External IP address of the vAIDC VM
      - name: grafana_url
        description: URL to access Grafana dashboards
      - name: gitea_url
        description: URL to access Gitea repository
      - name: argocd_url
        description: URL to access ArgoCD
      - name: prometheus_url
        description: URL to access Prometheus
      - name: ssh_command
        description: SSH command to connect to the VM
  requirements:
    roles:
      - level: Project
        roles:
          - roles/compute.admin
          - roles/iam.serviceAccountUser
    services:
      - compute.googleapis.com
